[package]
name = "pasture-algorithms"
version = "0.1.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2018"
license-file = "LICENSE"
description = "Point cloud algorithms for pasture"
homepage = "https://github.com/Mortano/pasture"
repository = "https://github.com/Mortano/pasture"
keywords = ["pasture", "pointcloud", "points", "lidar"]
categories = ["data-structures", "algorithms"]
readme = "README.md"

[dependencies]
pasture-core = { version = "=0.1.0", path = "../pasture-core" }
kd-tree = "0.3.0"
pasture-derive = { version = "=0.1.0", path = "../pasture-derive" }
typenum = "1.13.0"
rand = "0.8.3"
pasture-io = { version = "=0.1.0", path = "../pasture-io" }
rayon = "1.5"